/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TestResult {
    wpm: bigint;
    duration: bigint;
    difficulty: string;
    testMode: TestMode;
    language: string;
    timestamp: Time;
    accuracy: number;
}
export enum TestMode {
    sentences = "sentences",
    custom = "custom",
    words = "words"
}
export interface backendInterface {
    getAllTestResults(): Promise<Array<TestResult>>;
    getAverageAccuracy(): Promise<number | null>;
    getAverageWPM(): Promise<number | null>;
    getBestWPM(): Promise<bigint | null>;
    getDailyStreaks(): Promise<bigint>;
    getStreakCalendar(): Promise<Array<[Time, boolean]>>;
    getTestResult(index: bigint): Promise<TestResult>;
    getTestResultRange(start: bigint, end: bigint): Promise<Array<TestResult>>;
    getTodaysResults(): Promise<Array<TestResult>>;
    getTotalTests(): Promise<bigint>;
    isRegistered(): Promise<boolean>;
    submitTestResult(wpm: bigint, accuracy: number, testMode: TestMode, language: string, difficulty: string, duration: bigint): Promise<void>;
}
import type { TestMode as _TestMode, TestResult as _TestResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllTestResults(): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestResults();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestResults();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageAccuracy(): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageAccuracy();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageAccuracy();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageWPM(): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageWPM();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageWPM();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestWPM(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestWPM();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestWPM();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyStreaks(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyStreaks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyStreaks();
            return result;
        }
    }
    async getStreakCalendar(): Promise<Array<[Time, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakCalendar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakCalendar();
            return result;
        }
    }
    async getTestResult(arg0: bigint): Promise<TestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResult(arg0);
                return from_candid_TestResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResult(arg0);
            return from_candid_TestResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestResultRange(arg0: bigint, arg1: bigint): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResultRange(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResultRange(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysResults(): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysResults();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysResults();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalTests(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTests();
            return result;
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async submitTestResult(arg0: bigint, arg1: number, arg2: TestMode, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestResult(arg0, arg1, to_candid_TestMode_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestResult(arg0, arg1, to_candid_TestMode_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_TestMode_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestMode): TestMode {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TestResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestResult): TestResult {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wpm: bigint;
    duration: bigint;
    difficulty: string;
    testMode: _TestMode;
    language: string;
    timestamp: _Time;
    accuracy: number;
}): {
    wpm: bigint;
    duration: bigint;
    difficulty: string;
    testMode: TestMode;
    language: string;
    timestamp: Time;
    accuracy: number;
} {
    return {
        wpm: value.wpm,
        duration: value.duration,
        difficulty: value.difficulty,
        testMode: from_candid_TestMode_n4(_uploadFile, _downloadFile, value.testMode),
        language: value.language,
        timestamp: value.timestamp,
        accuracy: value.accuracy
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentences: null;
} | {
    custom: null;
} | {
    words: null;
}): TestMode {
    return "sentences" in value ? TestMode.sentences : "custom" in value ? TestMode.custom : "words" in value ? TestMode.words : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestResult>): Array<TestResult> {
    return value.map((x)=>from_candid_TestResult_n2(_uploadFile, _downloadFile, x));
}
function to_candid_TestMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestMode): _TestMode {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestMode): {
    sentences: null;
} | {
    custom: null;
} | {
    words: null;
} {
    return value == TestMode.sentences ? {
        sentences: null
    } : value == TestMode.custom ? {
        custom: null
    } : value == TestMode.words ? {
        words: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
