/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TestMode = IDL.Variant({
  'sentences' : IDL.Null,
  'custom' : IDL.Null,
  'words' : IDL.Null,
});
export const Time = IDL.Int;
export const TestResult = IDL.Record({
  'wpm' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : IDL.Text,
  'testMode' : TestMode,
  'language' : IDL.Text,
  'timestamp' : Time,
  'accuracy' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllTestResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getAverageAccuracy' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getAverageWPM' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getBestWPM' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getDailyStreaks' : IDL.Func([], [IDL.Nat], ['query']),
  'getStreakCalendar' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, IDL.Bool))],
      ['query'],
    ),
  'getTestResult' : IDL.Func([IDL.Nat], [TestResult], ['query']),
  'getTestResultRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TestResult)],
      ['query'],
    ),
  'getTodaysResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getTotalTests' : IDL.Func([], [IDL.Nat], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'submitTestResult' : IDL.Func(
      [IDL.Nat, IDL.Float64, TestMode, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TestMode = IDL.Variant({
    'sentences' : IDL.Null,
    'custom' : IDL.Null,
    'words' : IDL.Null,
  });
  const Time = IDL.Int;
  const TestResult = IDL.Record({
    'wpm' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : IDL.Text,
    'testMode' : TestMode,
    'language' : IDL.Text,
    'timestamp' : Time,
    'accuracy' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllTestResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getAverageAccuracy' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getAverageWPM' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getBestWPM' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getDailyStreaks' : IDL.Func([], [IDL.Nat], ['query']),
    'getStreakCalendar' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, IDL.Bool))],
        ['query'],
      ),
    'getTestResult' : IDL.Func([IDL.Nat], [TestResult], ['query']),
    'getTestResultRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'getTodaysResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getTotalTests' : IDL.Func([], [IDL.Nat], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'submitTestResult' : IDL.Func(
        [IDL.Nat, IDL.Float64, TestMode, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };