/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type TestMode = { 'sentences' : null } |
  { 'custom' : null } |
  { 'words' : null };
export interface TestResult {
  'wpm' : bigint,
  'duration' : bigint,
  'difficulty' : string,
  'testMode' : TestMode,
  'language' : string,
  'timestamp' : Time,
  'accuracy' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllTestResults' : ActorMethod<[], Array<TestResult>>,
  'getAverageAccuracy' : ActorMethod<[], [] | [number]>,
  'getAverageWPM' : ActorMethod<[], [] | [number]>,
  'getBestWPM' : ActorMethod<[], [] | [bigint]>,
  'getDailyStreaks' : ActorMethod<[], bigint>,
  'getStreakCalendar' : ActorMethod<[], Array<[Time, boolean]>>,
  'getTestResult' : ActorMethod<[bigint], TestResult>,
  'getTestResultRange' : ActorMethod<[bigint, bigint], Array<TestResult>>,
  'getTodaysResults' : ActorMethod<[], Array<TestResult>>,
  'getTotalTests' : ActorMethod<[], bigint>,
  'isRegistered' : ActorMethod<[], boolean>,
  'submitTestResult' : ActorMethod<
    [bigint, number, TestMode, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];